### ISSUE TITLE
Comparison to Cython?

### ISSUE THREAD

**Issue by franz101** [nicholasharris/CUDA-Parallel-Genetic-Algorithm-using-Python-Numba#1]
I have been researching and I found the following article:
https://blakeaw.github.io/2019-09-05-galibrate/

Cython seems to also vastly increase the speed.
The genetic algorithm framework gift uses mpi4py
for multiprocessing.

And lastly this article:
https://blog.paperspace.com/genetic-algorithm-python-cython-speed-increase/

**Comment by nicholasharris** [comment]
I have not used Cython personally. One of the articles you linked claims an 18x speedup, which is pretty close to what I found with my GPU code, at least on the one evaluation task tested. It's possible a more expensive evaluation task would find greater speedup on the GPU.  

It also seems to me there's no real reason you can't utilize both systems to some extent. At the very least, the Genetic Algorithm population operations (selection, mutation, crossover) could be done in compiled cython code for speedup on that end, with evaluation done on the GPU.
