### ISSUE TITLE
 eval_genomes_kernel[blocks_per_grid, threads_per_block](chromosomes_flat, fitnesses, pop_size, chrom_size)

### ISSUE THREAD

**Issue by 20153403349** [nicholasharris/CUDA-Parallel-Genetic-Algorithm-using-Python-Numba#2]
hello,  
 This parameter  --**[blocks_per_grid, threads_per_block]** does not exist when function is defined, why can it be used when calling,。

when I run this code, it show me the wrong  that    ** TypeError: 'function' object is not subscriptable**

How can I solve this problem?

thank you

**Comment by nicholasharris** [comment]
That notation (with a function call given the parameters [blocks_per_grid, threads_per_block]) is for a kernel function, a function that runs on the GPU. If you are getting that error, I would check your installation of CUDA/numba. 

These resources should help you start out with CUDA, the second link is a programming guide for numba that explains the use of this kernel notation.

https://developer.nvidia.com/how-to-cuda-python

https://nyu-cds.github.io/python-numba/05-cuda/#:~:text=Numba%20supports%20CUDA%20GPU%20programming,direct%20access%20to%20NumPy%20arrays.
